### ISSUE TITLE
Two Requests

### ISSUE THREAD

**Issue by Shuunen** [whackashoe/antimoderate#4]
This is funny, there is 2 requests for the base64 encoded image : one for jpeg & one for png.

![image](https://cloud.githubusercontent.com/assets/439158/11459362/54a0844c-96d5-11e5-9552-50149db6a2fe.png)

Where does this come ?

By the way, your lib is working great, thanks :)

**Comment by whackashoe** [comment]
The jpg one is the one that exists as initial data. 

Line 248 in antimoderate.js

```
idata_img.src = idata;
```

It just is setting the input base64 to an Image var.

That is the first request, the second  is on line 245 in antimoderate.js

```
img.src = canvas.toDataURL();
```

This converts the canvas we drew on to data:image/png, and it shows up in network because we set the src attribute to it. (This is where blurred version is set to img)

Thanks glad you like it :)

**Comment by Shuunen** [comment]
Thanks for the explanation :)

Now I wonder if I could implement some mechanics server side on nodejs, like you want profile.jpg ? here is a tiny version of 1kb and then client side request for profile.jpg?size=large on document ready and use the async blurry to sharp image loading.

In this case the server would do the re-sizing job once and then serve this version until we ask him the same picture with size parameter. 

In the DOM it will be simply : 

```
<img src="profile.jpg" class="blurry-async">
```

**Comment by whackashoe** [comment]
Np. Yes an automatic system like that would be quite cool! Lemme know if
you decide to implement it, would love to check it out.

**Comment by Shuunen** [comment]
sure :)
